export default ngModule => {
	ngModule.constant('messageNames', {
		nameGame : "nameGame",
		namePlayer : "namePlayer",
		waitingToStart : "waitingToStart",
		standBy : "standBy",
		standingByReadyRequest : "standingByReadyRequest",
		readyRequest : "readyRequest",
		readyConfirm : "readyConfirm",
		lastReadyConfirm : "lastReadyConfirm",
		responseRequest : "responseRequest",
		guessRequest : "guessRequest",
		guessConfirm : "guessConfirm",
		guessRemain : "guessRemain",
		winner : "winner",
		endGame : "endGame",
		quit : "quit",
		screenInitialize: "screenInitialize",
		screenWelcome: "screenWelcome",
		screenReady: "screenReady",
		screenRequestPrompt: "screenRequestPrompt",
		screenRequestResponse: "screenRequestResponse",
		screenRequestGuess: "screenRequestGuess",
		screenRoundResults: "screenRoundResults",
		screenGameResultsOneWinner: "screenGameResultsOneWinner",
		screenGameResultsMultipleWinners: "screenGameResultsMultipleWinners",
		bannerRequestPrompt: "bannerRequestPrompt",
		bannerRequestResponse: "bannerRequestResponse",
		bannerRequestGuess: "bannerRequestGuess",
		bannerRoundResults: "bannerRoundResults",
		bannerGameResultsOneWinner: "bannerGameResultsOneWinner",
		bannerGameResultsMultipleWinners: "bannerGameResultsMultipleWinners",
		moreGuessing: "moreGuessing",
		allGuessed: "allGuessed",
		gameOver: "gameOver",
		anotherRound: "anotherRound",
		newRound: "newRound",
		wrongDisplay: "wrongDisplay",
		noWrongGuesses: "noWrongGuesses",
		guessedWrong: "guessedWrong",
		wrongGuess: "wrongGuess",
		rightDisplay: "rightDisplay",
		noRightDisplay: "noRightDisplay",
		noRightGuesses: "noRightGuesses",
		guessedRight: "guessedRight",
		rightGuesser: "rightGuesser",
		anotherRightGuesser: "anotherRightGuesser",
		oneRightGuesser: "oneRightGuesser",
		multiRightGuessers: "multiRightGuessers",
		unguessedDisplay: "unguessedDisplay",
		unguessedPlayers: "unguessedPlayers",
		oneUnguessedPlayer: "oneUnguessedPlayer",
		multipleRightToast: "multipleRightToast",
		oneRightToast: "oneRightToast",
		unguessedResponseToast: "unguessedResponseToast",
		noUnguessedResponseToast: "noUnguessedResponseToast",
		unguessedPlayersToast: "unguessedPlayersToast",
		noUnguessedPlayersToast: "noUnguessedPlayersToast",
		writerToast: "writerToast",
		wrongToast: "wrongToast",
		wrongPlayerToast: "wrongPlayerToast",
		rules: "rules"
	});
}
