export default ngModule => {
	ngModule.constant('messageNames', {
		nameGame : "nameGame",
		namePlayer : "namePlayer",
		waitingToStart : "waitingToStart",
		standBy : "standBy",
		standingByReadyRequest : "standingByReadyRequest",
		readyRequest : "readyRequest",
		readyConfirm : "readyConfirm",
		lastReadyConfirm : "lastReadyConfirm",
		promptConfirm : "promptConfirm",
		responseRequest : "responseRequest",
		responseConfirm : "responseConfirm",
		guessRequest : "guessRequest",
		guessConfirm : "guessConfirm",
		guessRemain : "guessRemain",
		winner : "winner",
		endGame : "endGame",
		quit : "quit",
		screenInitialize: "screenInitialize",
		screenWelcome: "screenWelcome",
		screenReady: "screenReady",
		screenRequestPrompt: "screenRequestPrompt",
		screenRequestResponse: "screenRequestResponse",
		screenRequestGuess: "screenRequestGuess",
		screenRoundResults: "screenRoundResults",
		screenGameResults: "screenGameResults",
		bannerRequestPrompt: "bannerRequestPrompt",
		bannerRequestResponse: "bannerRequestResponse",
		bannerRequestGuess: "bannerRequestGuess",
		bannerRoundResults: "bannerRoundResults",
		bannerGameResults: "bannerGameResults",
		moreGuessing: "moreGuessing",
		allGuessed: "allGuessed",
		gameOver: "gameOver",
		anotherRound: "anotherRound",
		newRound: "newRound",
		wrongDisplay: "wrongDisplay",
		noWrongGuesses: "noWrongGuesses",
		guessedWrong: "guessedWrong",
		wrongGuess: "wrongGuess",
		rightDisplay: "rightDisplay",
		noRightDisplay: "noRightDisplay",
		noRightGuesses: "noRightGuesses",
		guessedRight: "guessedRight",
		rightGuesser: "rightGuesser",
		anotherRightGuesser: "anotherRightGuesser",
		oneRightGuesser: "oneRightGuesser",
		multiRightGuessers: "multiRightGuessers",
		unguessedDisplay: "unguessedDisplay",
		noUnguessed: "noUnguessed",
		unguessedPlayers: "unguessedPlayers",
		oneUnguessedPlayer: "oneUnguessedPlayer"
	});
}
